name: empty_collections
description: provides empty collection classes with const constructor and access to remove methods (which differs from other unmodifiable implementations)
version: 2.0.0
author: Stephan Schröder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/empty_collections

environment:
  sdk: '>1.24.3 <3.0.0'

dev_dependencies:
  test: '>=1.3.0 <1.4.0'
